name: flu_go_jwt
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^8.1.4
  device_preview: ^1.2.0
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.2.4
  flutter_stripe: ^11.0.0
  flutter_svg: ^2.0.17
  geocoding: ^4.0.0
  go_router: ^14.6.2
  google_maps_flutter: ^2.12.2
  google_sign_in: ^6.3.0
  grpc: ^4.0.1
  intl_phone_field: ^3.2.0
  location: ^8.0.0
  path_url_strategy_module: ^1.0.2
  protobuf: ^3.1.0

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # mejor ser especifico de momento todo
  assets:
    - .env
    - assets/
    - shorebird.yaml
