name: flu_go_jwt
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^8.1.4
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_branch_sdk: ^8.3.1
  flutter_dotenv: ^5.2.1
  go_router: ^14.6.2
  google_sign_in: ^6.2.2
  grpc: ^4.0.1
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  http: ^1.2.2
  path_url_strategy_module: ^1.0.2
  protobuf: ^3.1.0
  shared_preferences: ^2.5.2

dev_dependencies:
  build_runner: ^2.4.13
  hive_ce_generator: ^1.8.2
  envied_generator: ^1.0.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
